n = int(input('Digite um valor: '))
print('_' * 20)
print('=' * 30)
print(f'{"TABUADA":^30}')
print('=' * 30)
print(f'{n} X  0 = {n*0}')
print(f'{n} X  1 = {n*1}')
print(f'{n} X  2 = {n*2}')
print(f'{n} X  3 = {n*3}')
print(f'{n} X  4 = {n*4}')
print(f'{n} X  5 = {n*5}')
print(f'{n} X  6 = {n*6}')
print(f'{n} X  7 = {n*7}')
print(f'{n} X  8 = {n*8}')
print(f'{n} X  9 = {n*9}')
print(f'{n} X 10 = {n*10}')
print('_' * 20)
