n = input('Escrevar algo: ')
print(f'Tipo primitivos {type(n)}')
print(f'Está em Maiúsculo = {n.isupper()}')
print(f'É Alfanumérico = {n.isalnum()}')
print(f'É Alfabético = {n.isalpha()}')
print(f'São dígitos = {n.isdigit()}')
print(f'São decimais = {n.isdecimal()}')
print(f'São números = {n.isnumeric()}')
print(f'String Identificador válido = {n.isidentifier()}')
print(f'Está em minúsculo = {n.islower()}')
print(f'É imprimível ou está vazia = {n.isprintable()}')
print(f'Só tem espaços = {n.isspace()}')
print(f'Está capitalizado = {n.istitle()}')
print(f'Se a string é vazia ou se todos os caracteres na string são ASCII = {n.isascii()}')
