nome = str(input('Digite seu nome completo: ')).strip()
print(f'Seu nome em maiúculas é {nome.upper()}')
print(f'Seu nome em minúsculas é {nome.lower()}')
tot_letras = nome.split()
juntar = ''.join(tot_letras)
print(f'Seu nome tem ao todo {len(juntar)} letras')
print(f'O primeiro nome é {tot_letras[0]} e ele tem {len(tot_letras[0])} letras')
